import type { Product } from "./types";

const reviewSeed = (
  entries: [string, string, number, string, string, string][],
  prefix: string,
) =>
  entries.map(([author, role, rating, date, title, body], i) => ({
    id: `${prefix}-r${i + 1}`,
    author,
    role,
    rating,
    date,
    title,
    body,
  }));

export const products: Product[] = [
  {
    id: "p-react-admin-pro",
    slug: "react-admin-pro",
    name: "React Admin Pro",
    tagline: "Operator-grade admin shell with 42 screens",
    summary:
      "A dense, keyboard-friendly admin system: role-aware navigation, data tables with server-side pagination patterns, and a settings architecture you can extend without fighting it.",
    description: [
      "React Admin Pro is built the way internal tools actually get used: keyboard first, dense by default, and honest about loading and error states. Every table ships with sorting, column visibility, sticky headers and empty states already designed.",
      "State is split into route-level data, feature stores and UI state, so replacing the mock service layer with your own REST or GraphQL endpoints is a single-folder change.",
    ],
    categorySlug: "admin-dashboards",
    price: 89,
    salePrice: 69,
    rating: 4.9,
    reviewCount: 214,
    sales: 3120,
    tech: ["React", "TypeScript", "Tailwind CSS", "TanStack Query", "Recharts", "Vite"],
    tags: ["admin", "data tables", "rbac", "charts", "dark mode"],
    features: [
      {
        title: "42 production screens",
        body: "Users, roles, billing, audit log, API keys, notifications and a settings hub — not three demo pages.",
      },
      {
        title: "Table system, not table copies",
        body: "One composable data-table primitive drives every list view: sorting, filters, bulk actions, column presets.",
      },
      {
        title: "Role-aware navigation",
        body: "Permission map drives the sidebar, route guards and action visibility from a single source of truth.",
      },
      {
        title: "Chart kit",
        body: "Eleven pre-themed Recharts compositions that respect your design tokens in light and dark mode.",
      },
    ],
    included: [
      "Full TypeScript source",
      "42 screens across 9 feature modules",
      "Composable data-table and form primitives",
      "Light and dark themes with token file",
      "Figma source file",
      "Setup and architecture documentation",
      "12 months of updates",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 3.4 or 4", "Basic TypeScript"],
    pages: 42,
    version: "3.4.1",
    updatedAt: "2026-08-24",
    releasedAt: "2024-11-05",
    tint: "indigo",
    preview: "dashboard",
    screens: [
      { label: "Overview", kind: "dashboard" },
      { label: "Analytics", kind: "analytics" },
      { label: "Settings", kind: "corporate" },
      { label: "Billing", kind: "ecommerce" },
    ],
    featured: true,
    bestSeller: true,
    reviews: reviewSeed(
      [
        [
          "Marcus Feld",
          "Staff Engineer, logistics platform",
          5,
          "2026-08-02",
          "Saved us a full quarter",
          "We replaced an ageing internal console with this in three weeks. The table primitive alone was worth the price — we deleted about 4k lines of bespoke code.",
        ],
        [
          "Priya Raghavan",
          "Founding engineer",
          5,
          "2026-07-18",
          "Architecture holds up",
          "Folder boundaries are sensible and nothing is buried under six layers of abstraction. Swapping the mock services for our API took an afternoon.",
        ],
        [
          "Tomas Lindqvist",
          "Freelance developer",
          4,
          "2026-06-29",
          "Excellent, docs could go deeper",
          "Really polished UI and great dark mode. I'd like more written guidance on the permissions layer, but reading the code was clear enough.",
        ],
      ],
      "react-admin-pro",
    ),
  },
  {
    id: "p-nexus-saas",
    slug: "nexus-saas",
    name: "Nexus SaaS",
    tagline: "Marketing site and product shell in one system",
    summary:
      "Everything a SaaS launch needs: a sharp marketing surface, onboarding, workspace switching, usage metering and billing screens sharing one token set.",
    description: [
      "Nexus pairs a conversion-focused marketing site with the app shell behind it, so your landing page and product stop looking like two different companies.",
      "Includes an onboarding flow with progress persistence, invite and team management screens, plan comparison, and usage dashboards designed for metered pricing.",
    ],
    categorySlug: "saas",
    price: 99,
    rating: 4.8,
    reviewCount: 167,
    sales: 2410,
    tech: ["React", "TypeScript", "Tailwind CSS", "TanStack Router", "Zod"],
    tags: ["saas", "onboarding", "billing", "marketing", "app shell"],
    features: [
      {
        title: "Marketing + app parity",
        body: "Shared typography, spacing and color tokens across both surfaces, with one theme file to edit.",
      },
      {
        title: "Onboarding that persists",
        body: "Multi-step flow with validation, resumable progress and a skip-safe checklist pattern.",
      },
      {
        title: "Usage and metering UI",
        body: "Quota bars, overage warnings and plan-change previews modelled on real metered pricing.",
      },
      {
        title: "Team and invites",
        body: "Seat management, pending invite states and role changes with optimistic feedback.",
      },
    ],
    included: [
      "Full TypeScript source",
      "34 screens: marketing, auth, onboarding, workspace, billing",
      "Form system with Zod schemas",
      "Email template layouts (HTML)",
      "Figma source file",
      "Documentation site source",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 34,
    version: "2.1.0",
    updatedAt: "2026-09-01",
    releasedAt: "2025-03-19",
    tint: "violet",
    preview: "analytics",
    screens: [
      { label: "Landing", kind: "landing" },
      { label: "Workspace", kind: "analytics" },
      { label: "Billing", kind: "dashboard" },
      { label: "Docs", kind: "corporate" },
    ],
    featured: true,
    isNew: true,
    reviews: reviewSeed(
      [
        [
          "Elena Duarte",
          "Product designer",
          5,
          "2026-08-21",
          "The details are right",
          "Focus states, empty states, error copy — the boring parts are all handled. That is what you're actually buying.",
        ],
        [
          "Samuel Okafor",
          "CTO, analytics startup",
          5,
          "2026-07-30",
          "Shipped our beta on it",
          "We launched a private beta nine days after purchase. The onboarding flow needed almost no change.",
        ],
      ],
      "nexus-saas",
    ),
  },
  {
    id: "p-stayora-hotel",
    slug: "stayora-hotel",
    name: "Stayora Hotel",
    tagline: "Boutique hotel site with a real booking flow",
    summary:
      "Room inventory, rate plans, availability calendar and a three-step booking journey with a summary panel that survives navigation.",
    description: [
      "Stayora is designed for independent hotels and small groups: editorial photography layouts, room comparison, seasonal rate plans and a booking flow that keeps the guest oriented.",
      "The availability calendar, rate logic and guest form are isolated behind a small service module, ready to point at a property management system.",
    ],
    categorySlug: "hospitality",
    price: 79,
    salePrice: 59,
    rating: 4.7,
    reviewCount: 98,
    sales: 1480,
    tech: ["React", "TypeScript", "Tailwind CSS", "date-fns"],
    tags: ["hotel", "booking", "calendar", "hospitality", "multi-language ready"],
    features: [
      {
        title: "Booking in three steps",
        body: "Dates and guests, room and rate, guest details — with a persistent summary and clear pricing breakdown.",
      },
      {
        title: "Rate plan modelling",
        body: "Seasonal rates, minimum stays, breakfast add-ons and cancellation policies expressed as data.",
      },
      {
        title: "Room comparison",
        body: "Side-by-side amenities, occupancy and gallery layouts that hold up with real photography.",
      },
      {
        title: "Local pages",
        body: "Dining, spa, offers, gallery and location pages with map placeholder ready to swap.",
      },
    ],
    included: [
      "Full TypeScript source",
      "21 pages including booking flow",
      "Availability calendar component",
      "Rate plan data model",
      "Figma source file",
      "Content editing guide",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 21,
    version: "1.8.2",
    updatedAt: "2026-07-14",
    releasedAt: "2025-01-22",
    tint: "amber",
    preview: "hospitality",
    screens: [
      { label: "Home", kind: "hospitality" },
      { label: "Rooms", kind: "ecommerce" },
      { label: "Booking", kind: "landing" },
      { label: "Offers", kind: "corporate" },
    ],
    featured: true,
    reviews: reviewSeed(
      [
        [
          "Claire Bennet",
          "Agency owner",
          5,
          "2026-06-11",
          "Client signed off in one round",
          "Delivered to a 14-room property. The booking summary panel was the part they cared about and it just worked.",
        ],
        [
          "Ivan Petrov",
          "Web developer",
          4,
          "2026-05-28",
          "Solid, calendar is the star",
          "Calendar component is genuinely reusable. I've since used it in an unrelated rental project.",
        ],
      ],
      "stayora-hotel",
    ),
  },
  {
    id: "p-dineflow-restaurant",
    slug: "dineflow-restaurant",
    name: "DineFlow Restaurant",
    tagline: "Menu, reservations and ordering for food businesses",
    summary:
      "A warm, photography-led restaurant site with a structured menu system, reservation widget and pickup ordering flow.",
    description: [
      "DineFlow treats the menu as data, not markup: categories, dietary tags, allergens, price variants and seasonal availability are all typed, so updating dishes never means editing JSX.",
      "Reservation and pickup ordering flows are separated behind service modules for easy integration with providers or your own API.",
    ],
    categorySlug: "restaurant",
    price: 69,
    rating: 4.6,
    reviewCount: 76,
    sales: 1120,
    tech: ["React", "TypeScript", "Tailwind CSS", "React Hook Form"],
    tags: ["restaurant", "menu", "reservations", "ordering"],
    features: [
      {
        title: "Menu as structured data",
        body: "Dietary tags, allergens, variants and availability windows typed end to end.",
      },
      {
        title: "Reservation widget",
        body: "Party size, date, time slots and special requests with graceful unavailable states.",
      },
      {
        title: "Pickup ordering",
        body: "Cart, modifiers and time-slot selection built for takeaway rather than shipping.",
      },
      {
        title: "Multi-location ready",
        body: "Location switcher with per-venue hours, menus and contact details.",
      },
    ],
    included: [
      "Full TypeScript source",
      "17 pages with menu and ordering flows",
      "Typed menu data model",
      "Reservation form with validation",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 17,
    version: "1.4.0",
    updatedAt: "2026-08-09",
    releasedAt: "2025-06-02",
    tint: "rose",
    preview: "restaurant",
    screens: [
      { label: "Home", kind: "restaurant" },
      { label: "Menu", kind: "ecommerce" },
      { label: "Reserve", kind: "landing" },
      { label: "Locations", kind: "corporate" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Nadia Haddad",
          "Freelance designer",
          5,
          "2026-07-04",
          "Beautiful typography",
          "It looks like a restaurant brand, not a template. The menu data model is a nice touch.",
        ],
      ],
      "dineflow-restaurant",
    ),
  },
  {
    id: "p-educore-school",
    slug: "educore-school",
    name: "EduCore School",
    tagline: "Admissions-focused site for schools and academies",
    summary:
      "Programme catalog, admissions journey, staff directory, term calendar and a parent portal entry point, all accessibility-reviewed.",
    description: [
      "EduCore is built around the admissions funnel: programme discovery, requirements, key dates, enquiry forms and application status messaging.",
      "Content-heavy pages are handled with a consistent editorial layout system, and the whole set has been checked against WCAG AA contrast and keyboard navigation.",
    ],
    categorySlug: "education",
    price: 74,
    rating: 4.7,
    reviewCount: 61,
    sales: 870,
    tech: ["React", "TypeScript", "Tailwind CSS", "React Hook Form", "Zod"],
    tags: ["school", "admissions", "calendar", "accessible"],
    features: [
      {
        title: "Admissions journey",
        body: "Multi-step enquiry and application forms with saved progress and clear requirement checklists.",
      },
      {
        title: "Programme catalog",
        body: "Filterable programmes by level, department and delivery mode with comparison view.",
      },
      {
        title: "Term calendar",
        body: "Academic year calendar with event categories, exports and printable term dates.",
      },
      {
        title: "Accessibility reviewed",
        body: "AA contrast, visible focus order, skip links and reduced-motion support throughout.",
      },
    ],
    included: [
      "Full TypeScript source",
      "24 pages including admissions flow",
      "Programme and staff data models",
      "Accessibility notes",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 24,
    version: "2.0.3",
    updatedAt: "2026-06-30",
    releasedAt: "2024-09-12",
    tint: "emerald",
    preview: "education",
    screens: [
      { label: "Home", kind: "education" },
      { label: "Programmes", kind: "ecommerce" },
      { label: "Admissions", kind: "landing" },
      { label: "Staff", kind: "corporate" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Grace Mwangi",
          "IT lead, independent school",
          5,
          "2026-05-19",
          "Accessibility was the reason",
          "We had a compliance requirement and this passed our audit with only minor copy changes.",
        ],
      ],
      "educore-school",
    ),
  },
  {
    id: "p-commercex",
    slug: "commercex",
    name: "CommerceX",
    tagline: "Faceted storefront with a four-step checkout",
    summary:
      "Catalog with real faceted search, variant-aware product pages, cart drawer and a checkout that handles address, shipping, payment and review.",
    description: [
      "CommerceX focuses on the two screens that decide revenue: catalog and checkout. Facets are URL-driven and shareable, and the checkout is broken into steps that each validate independently.",
      "Cart, pricing and inventory logic live in a headless module you can point at Shopify, Medusa or your own service.",
    ],
    categorySlug: "ecommerce",
    price: 109,
    salePrice: 84,
    rating: 4.8,
    reviewCount: 143,
    sales: 1960,
    tech: ["React", "TypeScript", "Tailwind CSS", "TanStack Query", "Zod"],
    tags: ["ecommerce", "checkout", "faceted search", "variants"],
    features: [
      {
        title: "URL-driven facets",
        body: "Every filter, sort and page lives in the URL, so search results are shareable and back-button safe.",
      },
      {
        title: "Variant-aware PDP",
        body: "Option matrices, stock states, price ranges and image switching handled properly.",
      },
      {
        title: "Four-step checkout",
        body: "Address, shipping, payment and review with per-step validation and a persistent order summary.",
      },
      {
        title: "Headless cart module",
        body: "Pricing, discounts and totals isolated from UI for provider-agnostic integration.",
      },
    ],
    included: [
      "Full TypeScript source",
      "29 screens including full checkout",
      "Headless cart and pricing module",
      "Faceted search implementation",
      "Figma source file",
      "Integration notes",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 29,
    version: "4.0.0",
    updatedAt: "2026-08-30",
    releasedAt: "2024-04-08",
    tint: "cyan",
    preview: "ecommerce",
    screens: [
      { label: "Catalog", kind: "ecommerce" },
      { label: "Product", kind: "landing" },
      { label: "Checkout", kind: "dashboard" },
      { label: "Account", kind: "analytics" },
    ],
    featured: true,
    bestSeller: true,
    reviews: reviewSeed(
      [
        [
          "Daniel Roth",
          "Lead frontend, DTC brand",
          5,
          "2026-08-14",
          "Checkout is the real value",
          "Step validation and the order summary behaviour matched what we'd have spent a month designing.",
        ],
        [
          "Aiko Tanaka",
          "Full-stack developer",
          5,
          "2026-07-27",
          "Facets done right",
          "URL-driven filters with no state duplication. Refreshingly boring code.",
        ],
      ],
      "commercex",
    ),
  },
  {
    id: "p-orbit-analytics",
    slug: "orbit-analytics",
    name: "Orbit Analytics",
    tagline: "Analytics console with a composable chart kit",
    summary:
      "Dashboards, cohort views, funnels and a query builder shell for teams that need to present data credibly.",
    description: [
      "Orbit is an analytics front end: date-range comparison, segment switching, funnel and retention layouts, plus a saved-view system.",
      "Fifteen chart compositions share one theming layer so light and dark mode never need per-chart fixes.",
    ],
    categorySlug: "admin-dashboards",
    price: 94,
    rating: 4.7,
    reviewCount: 88,
    sales: 1030,
    tech: ["React", "TypeScript", "Tailwind CSS", "Recharts", "TanStack Query"],
    tags: ["analytics", "charts", "funnels", "cohorts"],
    features: [
      {
        title: "15 themed charts",
        body: "Line, area, bar, stacked, funnel, retention grid and sparklines with shared tokens.",
      },
      {
        title: "Comparison built in",
        body: "Date-range compare, delta badges and trend direction handled at the component level.",
      },
      {
        title: "Saved views",
        body: "Segment, filter and layout combinations persisted and shareable by URL.",
      },
      {
        title: "Export patterns",
        body: "CSV and image export affordances with clear pending and failure states.",
      },
    ],
    included: [
      "Full TypeScript source",
      "26 screens",
      "Chart kit with theming layer",
      "Saved-view architecture",
      "Documentation",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Recharts 2"],
    pages: 26,
    version: "1.9.4",
    updatedAt: "2026-08-18",
    releasedAt: "2025-02-11",
    tint: "indigo",
    preview: "analytics",
    screens: [
      { label: "Dashboard", kind: "analytics" },
      { label: "Funnels", kind: "dashboard" },
      { label: "Cohorts", kind: "corporate" },
      { label: "Reports", kind: "ecommerce" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Lucas Meyer",
          "Data engineer",
          5,
          "2026-08-05",
          "Charts finally match our theme",
          "One theming layer for every chart. I stopped writing per-chart color overrides entirely.",
        ],
      ],
      "orbit-analytics",
    ),
  },
  {
    id: "p-meridian-corporate",
    slug: "meridian-corporate",
    name: "Meridian Corporate",
    tagline: "Credible B2B presence with case studies",
    summary:
      "Services, sectors, case studies, investor relations, careers and a newsroom — structured for companies with real content volume.",
    description: [
      "Meridian is built for organisations that publish: a newsroom, case-study system, leadership pages and careers listings with filters.",
      "Layout primitives keep long-form pages readable, and every template holds up with 200 words or 2000.",
    ],
    categorySlug: "corporate",
    price: 79,
    rating: 4.6,
    reviewCount: 54,
    sales: 760,
    tech: ["React", "TypeScript", "Tailwind CSS"],
    tags: ["corporate", "case studies", "careers", "newsroom"],
    features: [
      {
        title: "Case-study system",
        body: "Problem, approach, outcome layout with metric callouts and related-work logic.",
      },
      {
        title: "Careers listings",
        body: "Filterable roles by team, location and type with a clean application entry point.",
      },
      {
        title: "Newsroom",
        body: "Article index, category pages, author cards and press-kit downloads.",
      },
      {
        title: "Long-form primitives",
        body: "Prose, pull-quote, figure and table blocks with consistent vertical rhythm.",
      },
    ],
    included: [
      "Full TypeScript source",
      "23 pages",
      "Long-form content primitives",
      "Careers and newsroom data models",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 23,
    version: "2.3.1",
    updatedAt: "2026-05-27",
    releasedAt: "2024-07-16",
    tint: "slate",
    preview: "corporate",
    screens: [
      { label: "Home", kind: "corporate" },
      { label: "Case study", kind: "portfolio" },
      { label: "Careers", kind: "ecommerce" },
      { label: "Newsroom", kind: "landing" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Helena Voss",
          "Marketing director",
          5,
          "2026-04-30",
          "Handles our content volume",
          "Most corporate templates collapse with real copy. This one has proper long-form layouts.",
        ],
      ],
      "meridian-corporate",
    ),
  },
  {
    id: "p-atelier-portfolio",
    slug: "atelier-portfolio",
    name: "Atelier Portfolio",
    tagline: "Editorial showcase for studios and creators",
    summary:
      "Typography-led project showcase with case-study layouts, image-forward grids and a restrained motion language.",
    description: [
      "Atelier is for work that should be the loudest thing on the page: generous type, controlled motion and grids that adapt to portrait and landscape work.",
      "Includes journal, about, services and contact pages plus a print-ready CV layout.",
    ],
    categorySlug: "portfolio",
    price: 59,
    salePrice: 44,
    rating: 4.8,
    reviewCount: 92,
    sales: 1340,
    tech: ["React", "TypeScript", "Tailwind CSS"],
    tags: ["portfolio", "editorial", "studio", "minimal"],
    features: [
      {
        title: "Case-study layouts",
        body: "Four project templates for brand, product, motion and photography work.",
      },
      {
        title: "Adaptive media grid",
        body: "Handles mixed aspect ratios without cropping decisions you didn't make.",
      },
      {
        title: "Restrained motion",
        body: "Reveal and hover interactions that respect prefers-reduced-motion by default.",
      },
      {
        title: "Print CV layout",
        body: "A dedicated print stylesheet for a clean single-page CV export.",
      },
    ],
    included: [
      "Full TypeScript source",
      "16 pages and 4 case-study templates",
      "Print stylesheet",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 16,
    version: "1.6.0",
    updatedAt: "2026-07-21",
    releasedAt: "2025-05-04",
    tint: "violet",
    preview: "portfolio",
    screens: [
      { label: "Index", kind: "portfolio" },
      { label: "Project", kind: "landing" },
      { label: "Journal", kind: "corporate" },
      { label: "About", kind: "education" },
    ],
    featured: false,
    isNew: true,
    reviews: reviewSeed(
      [
        [
          "Oscar Lindberg",
          "Studio founder",
          5,
          "2026-07-01",
          "Type choices are excellent",
          "I bought it for the case-study templates and stayed for the typography scale.",
        ],
      ],
      "atelier-portfolio",
    ),
  },
  {
    id: "p-launchpad-landing",
    slug: "launchpad-landing",
    name: "Launchpad Landing Kit",
    tagline: "Nine conversion pages with a shared block system",
    summary:
      "Waitlist, product launch, webinar, changelog and campaign pages assembled from 40 interchangeable content blocks.",
    description: [
      "Launchpad is a block system rather than nine fixed pages: hero, proof, feature, pricing, FAQ and CTA blocks compose into any campaign page in minutes.",
      "Every block ships in light and dark, with tested spacing rhythm so mixing them never breaks the page.",
    ],
    categorySlug: "landing-pages",
    price: 49,
    rating: 4.5,
    reviewCount: 118,
    sales: 2280,
    tech: ["React", "TypeScript", "Tailwind CSS"],
    tags: ["landing", "waitlist", "blocks", "campaign"],
    features: [
      {
        title: "40 content blocks",
        body: "Hero, logo strip, feature grid, comparison, pricing, testimonial, FAQ and CTA variants.",
      },
      {
        title: "Nine assembled pages",
        body: "Ready-made compositions for waitlist, launch, webinar, changelog and more.",
      },
      {
        title: "Form states included",
        body: "Waitlist and signup forms with validation, success, duplicate and failure states.",
      },
      {
        title: "Consistent rhythm",
        body: "Shared section spacing scale so any block order still looks intentional.",
      },
    ],
    included: [
      "Full TypeScript source",
      "40 blocks and 9 page compositions",
      "Form components with all states",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 9,
    version: "3.1.2",
    updatedAt: "2026-08-11",
    releasedAt: "2024-02-20",
    tint: "cyan",
    preview: "landing",
    screens: [
      { label: "Launch", kind: "landing" },
      { label: "Waitlist", kind: "portfolio" },
      { label: "Pricing", kind: "ecommerce" },
      { label: "Changelog", kind: "corporate" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Rita Alvarez",
          "Growth marketer",
          4,
          "2026-06-18",
          "Fast to assemble",
          "I put together three campaign pages in a day. Wish there were a few more testimonial variants.",
        ],
      ],
      "launchpad-landing",
    ),
  },
  {
    id: "p-harborview-resort",
    slug: "harborview-resort",
    name: "Harborview Resort",
    tagline: "Multi-property resort and villa rentals",
    summary:
      "Property switcher, villa inventory, seasonal packages, experience booking and a concierge enquiry flow.",
    description: [
      "Harborview handles groups with several properties: a property switcher drives inventory, rates, experiences and contact details from one data source.",
      "Experience booking is modelled separately from stays, so activities, spa and dining reservations don't fight the room flow.",
    ],
    categorySlug: "hospitality",
    price: 89,
    rating: 4.6,
    reviewCount: 47,
    sales: 610,
    tech: ["React", "TypeScript", "Tailwind CSS", "date-fns"],
    tags: ["resort", "villas", "multi-property", "experiences"],
    features: [
      {
        title: "Property switcher",
        body: "One data source drives inventory, rates, experiences and contact details per property.",
      },
      {
        title: "Experience booking",
        body: "Activities, spa and dining reservations modelled independently from room stays.",
      },
      {
        title: "Seasonal packages",
        body: "Bundle rooms with experiences and show clear savings breakdowns.",
      },
      {
        title: "Gallery system",
        body: "Lightbox galleries with keyboard navigation and lazy loading.",
      },
    ],
    included: [
      "Full TypeScript source",
      "25 pages across multi-property structure",
      "Experience booking module",
      "Gallery and lightbox components",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 25,
    version: "1.2.0",
    updatedAt: "2026-08-27",
    releasedAt: "2025-11-13",
    tint: "amber",
    preview: "hospitality",
    screens: [
      { label: "Resort", kind: "hospitality" },
      { label: "Villas", kind: "ecommerce" },
      { label: "Experiences", kind: "portfolio" },
      { label: "Enquiry", kind: "landing" },
    ],
    featured: false,
    isNew: true,
    reviews: reviewSeed(
      [
        [
          "Miguel Santos",
          "Digital lead, hotel group",
          5,
          "2026-08-25",
          "Multi-property was the blocker",
          "Every other template assumed one hotel. This one models a group properly.",
        ],
      ],
      "harborview-resort",
    ),
  },
  {
    id: "p-vaultpay-fintech",
    slug: "vaultpay-fintech",
    name: "VaultPay Fintech",
    tagline: "Payments dashboard and compliance-minded app shell",
    summary:
      "Transactions, payouts, disputes, KYC states and audit trails presented with the precision financial products demand.",
    description: [
      "VaultPay is built for payment products: transaction tables with reconciliation states, payout schedules, dispute timelines and KYC verification steps.",
      "Sensitive-data patterns like masked fields, reveal confirmations and audit trails are handled as first-class components.",
    ],
    categorySlug: "saas",
    price: 129,
    salePrice: 99,
    rating: 4.9,
    reviewCount: 73,
    sales: 690,
    tech: ["React", "TypeScript", "Tailwind CSS", "Recharts", "Zod"],
    tags: ["fintech", "payments", "compliance", "audit"],
    features: [
      {
        title: "Reconciliation-aware tables",
        body: "Transaction states, holds, refunds and partial captures represented honestly.",
      },
      {
        title: "Dispute timelines",
        body: "Evidence upload, deadline countdowns and status history in one view.",
      },
      {
        title: "KYC flows",
        body: "Verification steps with document upload, pending and rejected states.",
      },
      {
        title: "Sensitive-data patterns",
        body: "Masked fields, reveal confirmation and audit logging components.",
      },
    ],
    included: [
      "Full TypeScript source",
      "31 screens",
      "Sensitive-data component set",
      "Chart kit for financial series",
      "Figma source file",
      "Architecture documentation",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 31,
    version: "2.5.0",
    updatedAt: "2026-09-03",
    releasedAt: "2025-08-07",
    tint: "emerald",
    preview: "dashboard",
    screens: [
      { label: "Payments", kind: "dashboard" },
      { label: "Payouts", kind: "analytics" },
      { label: "Disputes", kind: "corporate" },
      { label: "KYC", kind: "landing" },
    ],
    featured: true,
    reviews: reviewSeed(
      [
        [
          "Anna Kowalski",
          "Engineering manager, payments",
          5,
          "2026-08-29",
          "Someone has shipped fintech before",
          "The state modelling for holds and partial captures told me this wasn't designed from screenshots.",
        ],
        [
          "Kwame Mensah",
          "Backend developer",
          5,
          "2026-08-12",
          "Audit patterns saved us",
          "The masked-field and audit-log components matched our compliance review almost exactly.",
        ],
      ],
      "vaultpay-fintech",
    ),
  },
  {
    id: "p-marketmesh-store",
    slug: "marketmesh-store",
    name: "MarketMesh Store",
    tagline: "Multi-vendor marketplace storefront",
    summary:
      "Vendor storefronts, split cart, seller ratings and an order-tracking view designed for marketplaces rather than single-brand shops.",
    description: [
      "MarketMesh handles what single-vendor templates ignore: carts split across sellers, per-vendor shipping, seller profiles and dispute entry points.",
      "Vendor onboarding and payout expectation screens are included as marketing surfaces for recruiting sellers.",
    ],
    categorySlug: "ecommerce",
    price: 119,
    rating: 4.5,
    reviewCount: 39,
    sales: 480,
    tech: ["React", "TypeScript", "Tailwind CSS", "TanStack Query"],
    tags: ["marketplace", "multi-vendor", "split cart", "seller"],
    features: [
      {
        title: "Split cart",
        body: "Grouped by vendor with independent shipping options and combined totals.",
      },
      {
        title: "Vendor storefronts",
        body: "Seller profile, catalog, policies and ratings with a consistent shell.",
      },
      {
        title: "Order tracking",
        body: "Per-shipment status timelines across multiple sellers in one order.",
      },
      {
        title: "Seller recruitment pages",
        body: "Onboarding, fees and payout explainer surfaces for growing supply.",
      },
    ],
    included: [
      "Full TypeScript source",
      "27 screens",
      "Split-cart module",
      "Vendor data models",
      "Figma source file",
    ],
    requirements: ["Node.js 20+", "React 18 or 19", "Tailwind CSS 4"],
    pages: 27,
    version: "1.1.3",
    updatedAt: "2026-07-08",
    releasedAt: "2026-01-15",
    tint: "rose",
    preview: "ecommerce",
    screens: [
      { label: "Marketplace", kind: "ecommerce" },
      { label: "Vendor", kind: "portfolio" },
      { label: "Cart", kind: "dashboard" },
      { label: "Tracking", kind: "analytics" },
    ],
    featured: false,
    reviews: reviewSeed(
      [
        [
          "Fatima Ali",
          "Product manager",
          4,
          "2026-06-22",
          "Split cart is rare",
          "Exactly the multi-vendor behaviour we needed. Docs on the vendor model could be longer.",
        ],
      ],
      "marketmesh-store",
    ),
  },
];

export const productBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const productById = (id: string) => products.find((p) => p.id === id);

export const allTech = Array.from(new Set(products.flatMap((p) => p.tech))).sort();
export const allTags = Array.from(new Set(products.flatMap((p) => p.tags))).sort();
